name: Format Code with Prettier

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write .
          only_changed: True
